"use client";

import React, { useState, useEffect } from 'react';
import DashboardShell from '@/components/layout/DashboardShell';
import {
    TrendingUp, BarChart3, Target, AlertTriangle,
    Download, Star, BookOpen, Zap, Activity, ArrowRight, Loader2
} from 'lucide-react';
import { useSession } from 'next-auth/react';
import { clsx } from 'clsx';
import { useRef } from 'react';
import jsPDF from 'jspdf';
import { toPng } from 'html-to-image';
import { toast } from 'sonner';

export default function ProgressPage() {
    const { data: session } = useSession();
    const [scoreData, setScoreData] = useState(null);
    const [sessions, setSessions] = useState([]);
    const [chartFilter, setChartFilter] = useState('7'); // '7' or 'all'
    const reportRef = useRef(null);
    const [isGenerating, setIsGenerating] = useState(false);

    useEffect(() => {
        if (!session?.user?.id) return;
        const fetchData = async () => {
            try {
                const [scoreRes, sessionsRes] = await Promise.all([
                    fetch(`/api/scores/${session.user.id}`),
                    fetch(`/api/sessions/${session.user.id}`)
                ]);

                const scoreData = await scoreRes.json();
                if (scoreData.success) setScoreData(scoreData.score);

                const sessionsData = await sessionsRes.json();
                if (sessionsData.success) setSessions(sessionsData.sessions);
            } catch (err) {
                console.error('Failed to fetch data', err);
            }
        };
        fetchData();
    }, [session]);

    const handleDownloadReport = async () => {
        if (!reportRef.current) return;
        setIsGenerating(true);
        const toastId = toast.loading("Generating your progress report...");

        try {
            const dataUrl = await toPng(reportRef.current, {
                cacheBust: true,
                backgroundColor: '#ffffff',
                style: {
                    borderRadius: '0',
                    transform: 'scale(1)',
                }
            });

            const img = new Image();
            img.src = dataUrl;

            img.onload = () => {
                const pdf = new jsPDF({
                    orientation: 'portrait',
                    unit: 'px',
                    format: [img.width / 1.5, img.height / 1.5]
                });

                const width = pdf.internal.pageSize.getWidth();
                const height = pdf.internal.pageSize.getHeight();

                pdf.addImage(dataUrl, 'PNG', 0, 0, width, height);

                // Add branding overlay
                pdf.setFontSize(8);
                pdf.setTextColor(150);
                pdf.text('Generated by Akabando Atlas Literacy Platform', 20, height - 10);
                pdf.text(new Date().toLocaleDateString(), width - 70, height - 10);

                pdf.save(`Akabando_Progress_Report_${session?.user?.name || 'Student'}.pdf`);
                toast.success("Report downloaded successfully!", { id: toastId });
                setIsGenerating(false);
            };
        } catch (error) {
            console.error("PDF Generation failed:", error);
            toast.error("Failed to generate report. Please try again.", { id: toastId });
            setIsGenerating(false);
        }
    };

    const handleShareProgress = async () => {
        const shareData = {
            title: 'My Akabando Progress',
            text: `I've completed ${scoreData?.totalSessions || 0} reading sessions with ${scoreData?.overallAccuracy || 0}% accuracy! Join me on Akabando Atlas.`,
            url: window.location.origin
        };

        try {
            if (navigator.share) {
                await navigator.share(shareData);
            } else {
                await navigator.clipboard.writeText(`${shareData.text} ${shareData.url}`);
                toast.success("Progress copied to clipboard! Share it with your friends.");
            }
        } catch (err) {
            console.log('Share failed:', err);
        }
    };

    // Format progress chart
    const historyData = scoreData?.progressData || [];
    const history = chartFilter === '7'
        ? historyData.slice(-7).map(d => d.accuracy)
        : historyData.map(d => d.accuracy);

    // For 'all', we don't pad with zeros if there are items, but for '7' we pad to keep 7 slots
    const chartData = chartFilter === '7'
        ? [...Array(Math.max(0, 7 - history.length)).fill(0), ...history]
        : history;

    const labels = chartFilter === '7'
        ? ['S1', 'S2', 'S3', 'S4', 'S5', 'S6', 'S7']
        : history.map((_, i) => `S${i + 1}`);

    const avgAccuracy = scoreData?.overallAccuracy || 0;

    // Real mistake summary
    const ms = scoreData?.mistakeSummary || {};
    const omissions = ms.Omission ?? 0;
    const mispronunciations = ms.Mispronunciation ?? 0;
    const substitutions = ms.Substitution ?? 0;
    const insertions = ms.Insertion ?? 0;
    const totalSessions = scoreData?.totalSessions || 0;
    const improvementPct = Math.max(0, avgAccuracy - (history[0] ?? avgAccuracy));

    // Real skill proxies from session data
    const fluency = scoreData?.averageFluency ?? 0;
    const accuracySkill = avgAccuracy;
    // Vocab / comprehension proxy: low omissions → high vocab, cap at 95
    const vocabSkill = Math.min(95, Math.max(0, 100 - omissions * 2));
    // Sentence structure proxy: low substitutions/insertions
    const structureSkill = Math.min(95, Math.max(0, 100 - (substitutions + insertions) * 2));

    return (
        <DashboardShell role="Student">
            <div className="mb-12 flex flex-col md:flex-row md:items-center justify-between gap-6 animate-in fade-in slide-in-from-left duration-700">
                <div>
                    <h1 className="text-5xl font-extrabold text-gray-900 tracking-tight mb-3">Your Progress</h1>
                    <p className="text-xl text-gray-500 font-medium">Visualize your growth and identify areas for improvement.</p>
                </div>
                <button
                    onClick={handleDownloadReport}
                    disabled={isGenerating}
                    className="glass-pill flex items-center space-x-3 px-8 py-4 text-gray-600 font-bold hover:bg-white/80 transition-all border-white/40 shadow-sm disabled:opacity-50"
                >
                    {isGenerating ? <Loader2 className="animate-spin h-5 w-5 mr-1" /> : <Download className="h-5 w-5 mr-1" />}
                    <span>{isGenerating ? "Processing..." : "Download Report"}</span>
                </button>
            </div>

            <div ref={reportRef} className="p-4 bg-white/50 rounded-[40px] mb-8">
                <div className="flex items-center justify-between p-8 border-b border-black/5">
                    <div className="flex items-center">
                        <img src="/AkabandoAtlas Logo .png" className="h-12 w-auto object-contain" />
                        <div className="ml-4">
                            <p className="text-[10px] font-black uppercase tracking-[0.3em] text-gray-400">Official Progress Report</p>
                            <p className="text-xl font-black text-black">{session?.user?.name}</p>
                        </div>
                    </div>
                    <div className="text-right">
                        <p className="text-[10px] font-black uppercase tracking-[0.3em] text-gray-400">Student ID</p>
                        <p className="text-sm font-bold text-black opacity-40">#{session?.user?.id?.slice(-8).toUpperCase()}</p>
                    </div>
                </div>

                <div className="grid grid-cols-1 lg:grid-cols-3 gap-10 mb-12">
                    {/* Main Analytics Card */}
                    <div className="lg:col-span-2 space-y-10">
                        <div className="glass-panel p-10 rounded-[60px] relative overflow-hidden group border-white/40 shadow-xl">
                            <div className="absolute top-0 right-0 p-12 opacity-5 group-hover:scale-110 transition-transform duration-[2s] pointer-events-none">
                                <Activity size={200} className="text-black" />
                            </div>

                            <div className="flex items-center justify-between mb-12 relative z-10">
                                <div>
                                    <h3 className="font-bold text-gray-900 text-2xl flex items-center">
                                        <BarChart3 className="h-6 w-6 text-gray-400 mr-4" /> Literacy Growth
                                    </h3>
                                    <div className="flex items-center mt-2 text-[10px] font-black uppercase tracking-widest text-green-500">
                                        <TrendingUp size={12} className="mr-2" /> Overall Accuracy: {avgAccuracy}%
                                    </div>
                                </div>
                                <div className="flex bg-white/40 backdrop-blur-md border border-white/40 p-1 rounded-full shadow-sm">
                                    <button
                                        onClick={() => setChartFilter('7')}
                                        className={clsx(
                                            "px-6 py-2 rounded-full text-[10px] font-bold uppercase tracking-widest transition-all",
                                            chartFilter === '7' ? "bg-black text-white shadow-lg" : "text-gray-400 hover:text-black"
                                        )}
                                    >
                                        Last 7
                                    </button>
                                    <button
                                        onClick={() => setChartFilter('all')}
                                        className={clsx(
                                            "px-6 py-2 rounded-full text-[10px] font-bold uppercase tracking-widest transition-all",
                                            chartFilter === 'all' ? "bg-black text-white shadow-lg" : "text-gray-400 hover:text-black"
                                        )}
                                    >
                                        All Time
                                    </button>
                                </div>
                            </div>

                            {/* Chart */}
                            <div className="h-80 flex items-end justify-between gap-6 px-4 relative z-10 overflow-x-auto scrollbar-hide">
                                {chartData.map((v, i) => (
                                    <div key={i} className="flex-1 min-w-[30px] group/bar relative h-full">
                                        <div className="absolute inset-x-0 bottom-0 bg-white/20 rounded-full h-full border border-white/10" />
                                        <div
                                            className="absolute bottom-0 w-full bg-black rounded-full transition-all duration-1000 shadow-2xl group-hover:bg-gray-800"
                                            style={{ height: `${v}%` }}
                                        >
                                            <div className="absolute -top-14 left-1/2 -translate-x-1/2 opacity-0 group-hover/bar:opacity-100 transition-all duration-300 bg-black text-white text-[10px] px-4 py-2 rounded-2xl font-black shadow-2xl scale-90 group-hover/bar:scale-100 whitespace-nowrap">
                                                {v}%
                                            </div>
                                        </div>
                                    </div>
                                ))}
                            </div>
                            <div className="flex items-center justify-between mt-8 px-4 text-[10px] font-black text-gray-400 uppercase tracking-[0.3em] relative z-10 overflow-x-auto scrollbar-hide">
                                {labels.map(s => <span key={s} className="flex-1 text-center min-w-[30px]">{s}</span>)}
                            </div>
                        </div>

                        {/* Real Pattern Breakdown */}
                        <div className="glass-panel p-10 rounded-[60px] border-white/40 shadow-xl">
                            <div className="flex items-center justify-between mb-10">
                                <h3 className="font-bold text-gray-900 text-2xl flex items-center">
                                    <AlertTriangle className="h-6 w-6 text-gray-400 mr-4" /> Mistake Patterns
                                </h3>
                            </div>
                            {totalSessions === 0 ? (
                                <div className="text-center py-10 text-gray-400">
                                    <Activity className="mx-auto h-10 w-10 mb-3 opacity-30" />
                                    <p className="font-semibold">Complete reading sessions to see your mistake patterns.</p>
                                </div>
                            ) : (
                                <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                                    <PatternCard icon={Zap} label="Word Omissions" count={omissions} color="bg-orange-500"
                                        desc="Words skipped while reading. Connector words like 'the', 'and' are often omitted." />
                                    <PatternCard icon={Target} label="Mispronunciations" count={mispronunciations} color="bg-red-500"
                                        desc="Words said incorrectly. These include phoneme errors and consonant mixups." />
                                    <PatternCard icon={BookOpen} label="Substitutions" count={substitutions} color="bg-blue-500"
                                        desc="Words swapped for another word. Often phonetically similar ones." />
                                    <PatternCard icon={TrendingUp} label="Improvement" count={`+${Math.round(improvementPct)}%`} color="bg-green-500"
                                        desc="Accuracy gain from first to most recent session across all recorded sessions." />
                                </div>
                            )}
                        </div>
                    </div>

                    {/* Sidebar */}
                    <div className="space-y-10">
                        <div className="bg-black p-10 rounded-[60px] text-white shadow-3xl relative overflow-hidden group">
                            <div className="absolute top-0 right-0 p-12 opacity-10 group-hover:rotate-12 transition-all duration-1000">
                                <Star size={100} fill="currentColor" />
                            </div>
                            <div className="relative z-10">
                                <div className="h-20 w-20 bg-white/10 backdrop-blur-md rounded-3xl flex items-center justify-center mb-8 border border-white/20">
                                    <Star className="h-10 w-10 text-white fill-current" />
                                </div>
                                <h4 className="text-3xl font-black mb-4 leading-tight tracking-tight">
                                    {totalSessions >= 10 ? 'Top Reader!' : totalSessions >= 5 ? 'Making Progress!' : 'Getting Started!'}
                                </h4>
                                <p className="text-white/60 text-sm font-medium mb-10 leading-relaxed">
                                    You have completed {totalSessions} reading session{totalSessions !== 1 ? 's' : ''} on the platform.
                                    {totalSessions < 5 ? ' Keep going to unlock achievements!' : ' Your dedication is inspiring!'}
                                </p>
                                {/* <button 
                                onClick={handleShareProgress}
                                className="w-full bg-white text-black font-black py-5 rounded-2xl flex items-center justify-center hover:bg-gray-100 transition-all shadow-xl"
                            >
                                Share Progress <ArrowRight className="ml-3 h-5 w-5" />
                            </button> */}
                            </div>
                        </div>

                        {/* Real Skills */}
                        <div className="glass-panel p-10 rounded-[60px] border-white/40 shadow-xl">
                            <h3 className="font-black text-gray-400 uppercase tracking-[0.2em] text-[10px] mb-10">Skills Overview</h3>
                            <div className="space-y-10">
                                <SkillProgress label="Reading Accuracy" value={accuracySkill} />
                                <SkillProgress label="Flow & Fluency" value={fluency} />
                                <SkillProgress label="Vocabulary Range" value={vocabSkill} />
                                <SkillProgress label="Sentence Structure" value={structureSkill} />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div className="absolute top-0 left-0 -z-50 opacity-0 pointer-events-none">
                <div ref={reportRef} className="p-16 bg-white w-[800px] text-black font-sans">
                    {/* Header */}
                    <div className="flex items-center justify-between border-b-4 border-black pb-8 mb-12">
                        <div className="flex items-center">
                            <img src="/AkabandoAtlas Logo .png" className="h-20 w-auto object-contain" />
                            <div className="ml-6">
                                <h1 className="text-4xl font-black tracking-tighter uppercase leading-none">AKABANDO<br />Atlas</h1>
                                <p className="text-xs font-bold text-gray-500 uppercase tracking-widest mt-1">Official Student Performance Report</p>
                            </div>
                        </div>
                        <div className="text-right">
                            <p className="text-[10px] font-black uppercase tracking-widest text-gray-400">Date Generated</p>
                            <p className="text-sm font-bold">{new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' })}</p>
                        </div>
                    </div>

                    {/* Student Info */}
                    <div className="bg-gray-50 p-8 rounded-3xl grid grid-cols-2 gap-8 mb-12 border border-gray-100">
                        <div>
                            <p className="text-[10px] font-black uppercase tracking-widest text-gray-400 mb-1">Student Name</p>
                            <p className="text-2xl font-black">{session?.user?.name}</p>
                        </div>
                        <div className="text-right">
                            <p className="text-[10px] font-black uppercase tracking-widest text-gray-400 mb-1">Student ID</p>
                            <p className="text-sm font-bold opacity-40">#{session?.user?.id?.slice(-8).toUpperCase()}</p>
                        </div>
                    </div>

                    {/* Overall Summary */}
                    <div className="grid grid-cols-4 gap-4 mb-12">
                        <SummaryBox label="Overall Accuracy" value={`${scoreData?.overallAccuracy || 0}%`} color="text-black" />
                        <SummaryBox label="Average Fluency" value={`${scoreData?.averageFluency || 0}%`} color="text-black" />
                        <SummaryBox label="Total Sessions" value={totalSessions} color="text-black" />
                        <SummaryBox label="Total Time" value={improvementPct > 0 ? `+${Math.round(improvementPct)}% Gain` : "-"} color="text-green-500" />
                    </div>

                    {/* Recent Sessions Table */}
                    <div className="mb-12">
                        <h2 className="text-xl font-black uppercase tracking-widest mb-6 border-l-4 border-black pl-4">Session History</h2>
                        <table className="w-full text-left border-collapse">
                            <thead>
                                <tr className="border-b border-gray-200">
                                    <th className="py-4 text-[10px] font-black uppercase tracking-widest text-gray-400">Date</th>
                                    <th className="py-4 text-[10px] font-black uppercase tracking-widest text-gray-400">Accuracy</th>
                                    <th className="py-4 text-[10px] font-black uppercase tracking-widest text-gray-400">Fluency</th>
                                    <th className="py-4 text-[10px] font-black uppercase tracking-widest text-gray-400 text-right">Duration</th>
                                </tr>
                            </thead>
                            <tbody>
                                {sessions.slice(0, 10).map((s, i) => (
                                    <tr key={i} className="border-b border-gray-50">
                                        <td className="py-4 font-bold text-sm">{new Date(s.completedAt).toLocaleDateString()}</td>
                                        <td className="py-4 font-black">{s.accuracy}%</td>
                                        <td className="py-4 font-bold text-gray-500">{s.fluencyScore || 0}%</td>
                                        <td className="py-4 font-bold text-gray-400 text-right">{s.duration || 0}s</td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>

                    {/* Omissions & Mistakes Table */}
                    <div>
                        <h2 className="text-xl font-black uppercase tracking-widest mb-6 border-l-4 border-red-500 pl-4">Detailed Mistake Analysis (Omissions & Substitutions)</h2>
                        <table className="w-full text-left border-collapse">
                            <thead>
                                <tr className="border-b border-gray-200">
                                    <th className="py-4 text-[10px] font-black uppercase tracking-widest text-gray-400">Word</th>
                                    <th className="py-4 text-[10px] font-black uppercase tracking-widest text-gray-400">Mistake Type</th>
                                    <th className="py-4 text-[10px] font-black uppercase tracking-widest text-gray-400">Session Date</th>
                                </tr>
                            </thead>
                            <tbody>
                                {sessions
                                    .flatMap(s => s.mistakes.map(m => ({ ...m, sessionDate: s.completedAt })))
                                    .filter(m => m.type === 'Omission' || m.type === 'Substitution' || m.type === 'Mispronunciation')
                                    .slice(0, 15)
                                    .map((m, i) => (
                                        <tr key={i} className="border-b border-gray-50">
                                            <td className="py-4 font-bold">{m.word}</td>
                                            <td className={`py-4 font-black uppercase text-[10px] ${m.type === 'Omission' ? 'text-orange-500' : 'text-red-500'}`}>
                                                {m.type}
                                            </td>
                                            <td className="py-4 font-bold text-sm text-gray-400">{new Date(m.sessionDate).toLocaleDateString()}</td>
                                        </tr>
                                    ))
                                }
                            </tbody>
                        </table>
                        {sessions.flatMap(s => s.mistakes).length > 15 && (
                            <p className="mt-4 text-[10px] text-gray-400 font-bold italic">* Showing recent 15 mistake records for brevity.</p>
                        )}
                    </div>

                    <div className="mt-20 pt-8 border-t border-gray-100 text-center">
                        <p className="text-[10px] font-black uppercase tracking-[0.4em] text-gray-300">Akabando Atlas Literacy Platform - Certificate of Progress</p>
                    </div>
                </div>
            </div>

        </DashboardShell>
    );
}

function SummaryBox({ label, value, color }) {
    return (
        <div className="bg-gray-50 p-6 rounded-3xl border border-gray-100">
            <p className="text-[9px] font-black uppercase tracking-widest text-gray-400 mb-2">{label}</p>
            <p className={`text-3xl font-black ${color}`}>{value}</p>
        </div>
    );
}

function PatternCard({ icon: Icon, label, count, color, desc }) {
    return (
        <div className="glass-panel p-8 rounded-4xl border-white/40 hover:bg-white hover:-translate-y-2 transition-all duration-500 group">
            <div className="flex items-center justify-between mb-6">
                <div className={clsx(color, 'p-4 rounded-3xl text-white shadow-lg')}>
                    <Icon size={20} />
                </div>
                <span className="text-3xl font-black text-gray-900">{count}</span>
            </div>
            <h4 className="font-bold text-gray-900 text-lg mb-2 group-hover:text-black transition-colors">{label}</h4>
            <p className="text-xs text-gray-400 leading-relaxed font-semibold">{desc}</p>
        </div>
    );
}

function SkillProgress({ label, value }) {
    return (
        <div className="group">
            <div className="flex items-center justify-between mb-4 px-1">
                <span className="text-[10px] font-black text-gray-400 uppercase tracking-widest group-hover:text-black transition-colors">{label}</span>
                <span className="text-[10px] font-black text-black">{value}%</span>
            </div>
            <div className="w-full h-3 bg-gray-100 rounded-full overflow-hidden p-0.5 border border-white/40 shadow-inner">
                <div className="h-full bg-black rounded-full transition-all duration-[2s] shadow-lg" style={{ width: `${value}%` }} />
            </div>
        </div>
    );
}
